### ISSUE TITLE
Are the _enumeration.default values appropriate?

### ISSUE THREAD

**Issue by nautolycus** [COMCIFS/cif_ed#6]
According to @vaitkus, _I think that the current COMCIFS stance on default values is as follows: '<...> suggest we adopt a general principle that default values can be provided in the dictionaries if an error can be detected by derivation from values that are known to be present.' (see https://www.iucr.org/__data/iucr/lists/coredmg/msg00461.html). Does this value (and other similar ones) match this criterion?_

The affected items in this draft are:
 | Data item                                                   |  suggested default |
| --- | --- |
 | `_diffrn_measurement.method_precession`  | no |
 | `_diffrn_measurement.integration`                | rotation |
 | `_diffrn_measurement.tracking`                     | no |
 | `_diffrn_radiation.illumination_mode`            | parallel |
 | `_refine.diffraction_theory`                             | kinematical |

**Comment by jamesrhester** [comment]
I think none of these should have default values:

`_diffrn_measurement.method_precession`: should not have a default value, because it is possible that `precession_angle`, which would be the way of determining the value, is absent, indeed, that appears to be the intended approach if no precession was used.

`_diffrn_measurement.tracking`: also should have no default value, as there is no way to derive from `tracking_method`, which is plain text and could end up saying `None` or `.` or `None used` or `Tried it but it didn't work so didn't use it.`

`_diffrn_measurement.integration/illumination_mode/diffraction_theory`: also no, because the defaults are chosen purely based on the current most widespread technique. We don't know what will be popular ten or thirty years from now. Maybe dynamical calculations will be widespread with increases in computing power or popular code.
